enabled_fonts:
  - 'https://www.fontsquirrel.com/fonts/source-sans-pro#SourceSansProRegular'
  - 'https://www.fontsquirrel.com/fonts/source-sans-pro#SourceSansProBold'
load_all_enabled_fonts: 1
load_on_themes: {  }
_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
